---
#
# Playbook to install the ELK stack
#

- hosts: elk
#  remote_user: vagrant
  roles:
    - { role: elasticsearch }
    - { role: fluentd, when: (logging_backend == 'fluentd') }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: nginx }
    - { role: curator, when: install_curator_tool }
    - { role: kibana }
    - { role: redis }
